Improved Code
esx-framework/esx_boat pull request #19
Opened 2023-08-19 20:51 UTC by prvtfly

- Promised Based Database Querys
- Fixed Linter Errors
- Fixed Nestiness in this code
- Additonal Error Handling and a Function in the Config which can handle Cheater punishment
- Better naming

2023-08-19 21:09 UTC, prvtfly commented
awaiting pr

2023-08-19 21:42 UTC, Gellipapa requested changes
Hi! Thank you pr, please handle requests.

2023-08-19 21:42 UTC, Gellipapa commented on client/main.lua
> +        return ESX.CloseContext();
remove please ';' all code

2023-08-19 21:42 UTC, Gellipapa commented on client/main.lua
> +    local VEH_EXIT_CONTROL = 75;
Indent fix please

2023-08-19 21:42 UTC, Gellipapa commented on client/marker.lua
> +		local vehicle = GetVehiclePedIsIn(playerPed, false)
indent please

2023-08-19 21:42 UTC, Gellipapa commented on server/main.lua
> +	local storedBoats = ParkBoats()
indent please

2023-08-19 21:42 UTC, Gellipapa commented on server/main.lua
> +  if affectedRows > 0 then
indent please, format code.

2023-08-25 17:43 UTC, Gellipapa approved these changes
Hi! Well done, I'll test and merge.

2023-08-25 18:08 UTC, Gellipapa commented
@prvtfly Hi! This is not working i can't store boat, all time gettting "This is not my boat", i tested old version works correctly. I think you mistake in server side querys. Please fix this issue and test. Thanks.

2023-09-04 22:14 UTC, Gellipapa commented
@prvtfly Hi! Can you fix issues?

2023-09-04 22:16 UTC, prvtfly commented
Hey, I’ll have a look tomorrow!

2023-09-04 22:37 UTC, Gellipapa commented
> Hey, I’ll have a look tomorrow!

Thanks 😄

2023-09-23 15:27 UTC, closed without merging