Get correct label from config
esx-framework/esx_boat pull request #21
Opened 2023-10-02 04:46 UTC by RealKnoblauchbrot

Fix the issue of the vehicle label not getting correctly. 

Since `GetDisplayNameFromVehicleModel` uses the name from the vehicles.meta and some vehicles like the "seashark", "seashark2", "seashark3" share the same name: "seashark" it won't be able to return the correct vehicle name as listed in the config.

Issue mentioning this issue: #20

2023-10-02 04:51 UTC, RealKnoblauchbrot commented
Tested it of course

![grafik](https://github.com/esx-framework/esx_boat/assets/60825241/d9f2a8aa-33dc-4661-8aeb-66f5397314ec)

2023-10-02 15:10 UTC, Arctos2win commented
nope this is not the way bcs when any other resource adds 
a boat to a player his / her garage then the label of the boat will return nil if not in the config. 
i will fix this issue as soon as i have time since i know a way to do this without 
the need to add all labels to the config.

2023-11-05 12:05 UTC, Arctos2win requested changes

2023-11-05 12:05 UTC, Arctos2win commented on client/main.lua
> -	local model = string.lower(GetDisplayNameFromVehicleModel(hash))
keep this otherwise all vehicles that aren't in the config don't have a name.

2023-11-25 12:55 UTC, Gellipapa commented
@Arctos2win Hi! Can you tested this?

2023-12-16 13:31 UTC, Gellipapa commented
@Arctos2win Hi! Any status?

2024-02-29 20:30 UTC, Gellipapa commented
I made another pull request and I fixed this problem, i closed this pr.

2024-02-29 20:30 UTC, closed without merging